/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/main` | `/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/favorite-event` | `/favorite-event`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}/content/events-details` | `/content/events-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}/content/ticket-details` | `/content/ticket-details`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/main` | `/main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/favorite-event` | `/favorite-event`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(index)'}/content/events-details` | `/content/events-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(index)'}/content/ticket-details` | `/content/ticket-details`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/main${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(index)'}${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(index)'}${'/(tabs)'}/favorite-event${`?${string}` | `#${string}` | ''}` | `/favorite-event${`?${string}` | `#${string}` | ''}` | `${'/(index)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(index)'}${'/(tabs)'}/tickets${`?${string}` | `#${string}` | ''}` | `/tickets${`?${string}` | `#${string}` | ''}` | `${'/(index)'}/content/events-details${`?${string}` | `#${string}` | ''}` | `/content/events-details${`?${string}` | `#${string}` | ''}` | `${'/(index)'}/content/ticket-details${`?${string}` | `#${string}` | ''}` | `/content/ticket-details${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/main` | `/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/favorite-event` | `/favorite-event`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}/content/events-details` | `/content/events-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(index)'}/content/ticket-details` | `/content/ticket-details`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
