import {
  EventCategoryEnum,
  ReadEventCategoryDTO,
} from "@/types/category.types";

export const EventCategoryData: ReadEventCategoryDTO[] = [
  // Business & Professional
  {
    id: "0",
    name: EventCategoryEnum.Conferences,
    description: "Professional conferences and summits",
    iconName: "business-center",
    iconType: "MaterialIcons",
    color: "#8A2BE2",
  },
  {
    id: "1",
    name: EventCategoryEnum.NetworkingEvents,
    description: "Events for professional networking",
    iconName: "people",
    iconType: "MaterialIcons",
    color: "#4682B4",
  },
  {
    id: "2",
    name: EventCategoryEnum.TradeShows,
    description: "Industry trade shows and expos",
    iconName: "store",
    iconType: "MaterialIcons",
    color: "#FF6347",
  },
  {
    id: "3",
    name: EventCategoryEnum.Seminars,
    description: "Educational seminars and workshops",
    iconName: "school",
    iconType: "MaterialIcons",
    color: "#20B2AA",
  },
  {
    id: "4",
    name: EventCategoryEnum.ProductLaunches,
    description: "New product launch events",
    iconName: "new-releases",
    iconType: "MaterialIcons",
    color: "#FF4500",
  },

  // Technology & Innovation
  {
    id: "5",
    name: EventCategoryEnum.TechConferences,
    description: "Technology-focused conferences",
    iconName: "laptop",
    iconType: "MaterialIcons",
    color: "#00CED1",
  },
  {
    id: "6",
    name: EventCategoryEnum.Hackathons,
    description: "Coding and innovation hackathons",
    iconName: "code",
    iconType: "MaterialIcons",
    color: "#32CD32",
  },
  {
    id: "7",
    name: EventCategoryEnum.Webinars,
    description: "Online seminars and presentations",
    iconName: "video-call",
    iconType: "MaterialIcons",
    color: "#1E90FF",
  },
  {
    id: "8",
    name: EventCategoryEnum.StartupEvents,
    description: "Startup pitches and events",
    iconName: "rocket",
    iconType: "MaterialIcons",
    color: "#FF69B4",
  },
  {
    id: "9",
    name: EventCategoryEnum.AIandBlockchain,
    description: "AI and blockchain technology events",
    iconName: "memory",
    iconType: "MaterialIcons",
    color: "#9932CC",
  },

  // Entertainment & Lifestyle
  {
    id: "10",
    name: EventCategoryEnum.Concerts,
    description: "Live music concerts and festivals",
    iconName: "music-note",
    iconType: "MaterialIcons",
    color: "#FF4500",
  },
  {
    id: "11",
    name: EventCategoryEnum.MoviePremieres,
    description: "Film premiere events",
    iconName: "movie",
    iconType: "MaterialIcons",
    color: "#DC143C",
  },
  {
    id: "12",
    name: EventCategoryEnum.FashionShows,
    description: "Fashion and design showcases",
    iconName: "color-lens",
    iconType: "MaterialIcons",
    color: "#FF00FF",
  },
  {
    id: "13",
    name: EventCategoryEnum.ComedyShows,
    description: "Live comedy performances",
    iconName: "emoji-events",
    iconType: "MaterialIcons",
    color: "#F59762",
  },
  {
    id: "14",
    name: EventCategoryEnum.AwardCeremonies,
    description: "Award shows and galas",
    iconName: "star",
    iconType: "MaterialIcons",
    color: "#FFD700",
  },

  // Sports & Fitness
  {
    id: "15",
    name: EventCategoryEnum.Marathons,
    description: "Running races and marathons",
    iconName: "directions-run",
    iconType: "MaterialIcons",
    color: "#228B22",
  },
  {
    id: "16",
    name: EventCategoryEnum.YogaRetreats,
    description: "Yoga and wellness retreats",
    iconName: "self-improvement",
    iconType: "MaterialIcons",
    color: "#98FB98",
  },
  {
    id: "17",
    name: EventCategoryEnum.EsportsTournaments,
    description: "Competitive gaming tournaments",
    iconName: "sports-esports",
    iconType: "MaterialIcons",
    color: "#00BFFF",
  },
  {
    id: "18",
    name: EventCategoryEnum.ExtremeSports,
    description: "Extreme sports competitions",
    iconName: "skateboarding",
    iconType: "MaterialIcons",
    color: "#FF1493",
  },
  {
    id: "19",
    name: EventCategoryEnum.BodybuildingExpos,
    description: "Fitness and bodybuilding expos",
    iconName: "fitness-center",
    iconType: "MaterialIcons",
    color: "#FFA500",
  },

  // Education & Training
  {
    id: "20",
    name: EventCategoryEnum.Workshops,
    description: "Hands-on workshops and bootcamps",
    iconName: "build",
    iconType: "MaterialIcons",
    color: "#4169E1",
  },
  {
    id: "21",
    name: EventCategoryEnum.UniversityOpenDays,
    description: "University open house events",
    iconName: "school",
    iconType: "MaterialIcons",
    color: "#483D8B",
  },
  {
    id: "22",
    name: EventCategoryEnum.CareerFairs,
    description: "Job and career fairs",
    iconName: "work",
    iconType: "MaterialIcons",
    color: "#2F4F4F",
  },
  {
    id: "23",
    name: EventCategoryEnum.OnlineCourses,
    description: "Online educational courses",
    iconName: "laptop-mac",
    iconType: "MaterialIcons",
    color: "#6A5ACD",
  },
  {
    id: "24",
    name: EventCategoryEnum.StudentCompetitions,
    description: "Competitions for students",
    iconName: "emoji-events",
    iconType: "MaterialIcons",
    color: "#CD5C5C",
  },

  // Cultural & Community
  {
    id: "25",
    name: EventCategoryEnum.Festivals,
    description: "Cultural festivals and parades",
    iconName: "festival",
    iconType: "MaterialIcons",
    color: "#FFD700",
  },
  {
    id: "26",
    name: EventCategoryEnum.ReligiousGatherings,
    description: "Religious community events",
    iconName: "church",
    iconType: "MaterialIcons",
    color: "#DAA520",
  },
  {
    id: "27",
    name: EventCategoryEnum.CharityEvents,
    description: "Fundraising and charity events",
    iconName: "volunteer-activism",
    iconType: "MaterialIcons",
    color: "#FF69B4",
  },
  {
    id: "28",
    name: EventCategoryEnum.HeritageCelebrations,
    description: "Cultural heritage celebrations",
    iconName: "history-edu",
    iconType: "MaterialIcons",
    color: "#8B4513",
  },
  {
    id: "29",
    name: EventCategoryEnum.CommunityMeetups,
    description: "Local community gatherings",
    iconName: "groups",
    iconType: "MaterialIcons",
    color: "#3CB371",
  },

  // Food & Drinks
  {
    id: "30",
    name: EventCategoryEnum.FoodFestivals,
    description: "Culinary festivals and tastings",
    iconName: "restaurant",
    iconType: "MaterialIcons",
    color: "#CD853F",
  },
  {
    id: "31",
    name: EventCategoryEnum.WineTasting,
    description: "Wine and brewery tasting events",
    iconName: "wine-bar",
    iconType: "MaterialIcons",
    color: "#800080",
  },
  {
    id: "32",
    name: EventCategoryEnum.CookingClasses,
    description: "Cooking workshops and classes",
    iconName: "soup-kitchen",
    iconType: "MaterialIcons",
    color: "#F08080",
  },
  {
    id: "33",
    name: EventCategoryEnum.FarmersMarkets,
    description: "Local farmers' markets",
    iconName: "local-grocery-store",
    iconType: "MaterialIcons",
    color: "#9ACD32",
  },
  {
    id: "34",
    name: EventCategoryEnum.RestaurantOpenings,
    description: "New restaurant openings",
    iconName: "storefront",
    iconType: "MaterialIcons",
    color: "#DEB887",
  },

  // Arts & Creativity
  {
    id: "35",
    name: EventCategoryEnum.ArtExhibitions,
    description: "Art gallery exhibitions",
    iconName: "palette",
    iconType: "MaterialIcons",
    color: "#BA55D3",
  },
  {
    id: "36",
    name: EventCategoryEnum.TheaterPerformances,
    description: "Theater and dance shows",
    iconName: "theater-comedy",
    iconType: "MaterialIcons",
    color: "#FFA07A",
  },
  {
    id: "37",
    name: EventCategoryEnum.PoetryEvents,
    description: "Poetry readings and spoken word",
    iconName: "mic",
    iconType: "MaterialIcons",
    color: "#87CEEB",
  },
  {
    id: "38",
    name: EventCategoryEnum.FilmFestivals,
    description: "Photography and film festivals",
    iconName: "videocam",
    iconType: "MaterialIcons",
    color: "#FF8C00",
  },
  {
    id: "39",
    name: EventCategoryEnum.WritingWorkshops,
    description: "Writing and storytelling workshops",
    iconName: "edit",
    iconType: "MaterialIcons",
    color: "#4682B4",
  },

  // Science & Environment
  {
    id: "40",
    name: EventCategoryEnum.EnvironmentalSummits,
    description: "Summits on environmental issues",
    iconName: "eco",
    iconType: "MaterialIcons",
    color: "#228B22",
  },
  {
    id: "41",
    name: EventCategoryEnum.SpaceEvents,
    description: "Astronomy and space events",
    iconName: "telescope",
    iconType: "MaterialCommunityIcons",
    color: "#191970",
  },
  {
    id: "42",
    name: EventCategoryEnum.ScienceFairs,
    description: "Science exhibitions and fairs",
    iconName: "science",
    iconType: "MaterialIcons",
    color: "#00B7EB",
  },
  {
    id: "43",
    name: EventCategoryEnum.WildlifeConservation,
    description: "Wildlife conservation events",
    iconName: "pets",
    iconType: "MaterialIcons",
    color: "#8FBC8F",
  },
  {
    id: "44",
    name: EventCategoryEnum.GreenEnergyConferences,
    description: "Sustainable energy conferences",
    iconName: "bolt",
    iconType: "MaterialIcons",
    color: "#7FFF00",
  },

  // Family & Kids
  {
    id: "45",
    name: EventCategoryEnum.ChildrensWorkshops,
    description: "Workshops for children",
    iconName: "child-care",
    iconType: "MaterialIcons",
    color: "#FF69B4",
  },
  {
    id: "46",
    name: EventCategoryEnum.StorytellingSessions,
    description: "Storytelling for kids",
    iconName: "book",
    iconType: "MaterialIcons",
    color: "#DDA0DD",
  },
  {
    id: "47",
    name: EventCategoryEnum.FamilyFunDays,
    description: "Family-oriented fun days",
    iconName: "celebration",
    iconType: "MaterialIcons",
    color: "#00FF7F",
  },
  {
    id: "48",
    name: EventCategoryEnum.AmusementParkEvents,
    description: "Amusement park special events",
    iconName: "rollercoaster",
    iconType: "MaterialCommunityIcons",
    color: "#FF00FF",
  },
  {
    id: "49",
    name: EventCategoryEnum.ToyConventions,
    description: "Toy and game conventions",
    iconName: "toys",
    iconType: "MaterialIcons",
    color: "#FFFF00",
  },
  {
    id: "50",
    name: EventCategoryEnum.Funeral,
    description: "Funeral and memorial services",
    iconName: "event-seat",
    iconType: "MaterialIcons",
    color: "#F0635A",
  },
];
